bininfo/bininfo.go
This package does not have much to it on the inside, but it's a lynchpin in pushing a surprising number of repeated patterns from across all application repos down to the library level. For example:
We have something like this across several Makefiles:
https://github.com/sapcc/absent-metrics-operator/blob/c563e77702a7f912962a16904daddda2fae79488/Makefile.maker.yaml#L40-L46
We cannot centralize this because the targeted variables are always on the application level, at places that are hard to predict. By having these be in this central place instead, we can have go-makefile-maker autogenerate the linker flags automatically whenever go-api-declarations shows up in the dependency list.
We have something like this across several applications: …
=> add package bininfo

limes/resources/metadata.go, limes/resources/report_cluster.go, limes/resources/report_domain.go, limes/resources/report_project.go
Companion PR for https://github.com/sapcc/limes/pull/264. The QuotaDistributionModel must become part of the public API because we will adjust the display and behavior of the UI controls in Elektra based on it.
=> limes: add QuotaDistributionModel enum

deployevent/deployevent.go, tensoevent/tensoevent.go
i need to add terraform runs to the tenso events and want to use the concourse release resources
i moved the helmevent package into tensoevent and made the helm releases field nullable.
i then added the TFRelease struct and it's dependencies to it.
=> [WIP] Generalize helmevent to tensoevent

cadf/event.go
Name is not supported in all events as a resource. It needs to be omitempty to not show a blank name where it is unavailable. 
I will also be adding more support for the name field through metis enrichment. However even in the case that this is unavailable, it needs to not show up as empty as it's confusing for customers.
=> CADF: Name in resource field is not supported in all events. Omitempty

limes/resources/report_cluster.go, limes/resources/report_domain.go, limes/resources/report_project.go
As discussed earlier today.
For the domain-level and cloud-level UIs, they will serve to generate overviews, before drilling down into the commitments of specific projects.
For the project-level UI, they will remove the need for the UI to query for the full list of commitments only to mark resources that have pending or planned commitments at all.
=> limes: add additional aggregations of commitment numbers

limes/resources/overrides.go, limes/resources/overrides_test.go
I want to reuse this in limesctl for CI-level validation of quota-overrides.json files.
This slightly differs from [the existing implementation in Limes core](https://github.com/sapcc/limes/blob/753afb2a34a9fab1cc970cf373acb7c0c2f57f43/internal/core/cluster.go#L183-L236):
- To uncouple from the `core.Cluster` structure, this uses a callback to learn about which resources exist and which units they use.
- I also used the opportunity to refactor out the innermost loop into a helper function for readability.
- Because this is below go-bits, any go-bits APIs were replaced by their std equivalents (in the case of `errext.ErrorSet -> []error`) or replaced with a simple inline implementation (in the case of `assert.DeepEqual`).
=> limes: move ParseQuotaOverrides function down a few layers

limes/resources/report_project.go
I'm torn what's better, either add the atribute to the API declaration or wrap the historical_usage in another struct on the API side. I think this approach is cleaner.
If this approach is agreeable, then I will push a new tag `v1.11.3` and update the vendor on the limes repo.
=> Add historical usage to AZ report

limes/metadata.go, limes/resources/metadata.go, limes/resources/overrides.go, limes/unit.go, liquid/availability_zone.go, liquid/doc.go, liquid/info.go, liquid/metrics.go, liquid/overcommit_factor.go, liquid/overcommit_factor_test.go, liquid/quota.go, liquid/report_capacity.go, liquid/report_usage.go, liquid/subdivisions.go, liquid/unit.go
LIQUID is the protocol spec for a decoupling effort in which I want to isolate the service-specific quota/usage/capacity scraping and quota setting logic within Limes and make those more pluggable, and also make some improvements to the internal architecture of Limes along the way.
LIQUID is derived from the existing [internal `QuotaPlugin` and `CapacityPlugin` interfaces in Limes](https://github.com/sapcc/limes/blob/master/internal/core/plugin.go), but turned from an internal Go interface to an OpenStack-like REST API. Some more notes on specific parts of the design:
* Before writing the spec like this, I did a trial run with OpenAPI (aka Swagger) and found OpenAPI type definitions significantly more tedious to write than straight-up Go types, with not a lot of gain from all that …
=> add spec and types for LIQUID

limes/resources/commitment.go
Reason: DB field is now handled as a unique key
=> Change transfer token type to a pointer

liquid/info.go, liquid/quota.go, liquid/report_usage.go
While trying to convert the QuotaPlugin for Manila into a liquid, I noticed that its share type configuration matches projects and domains by name. So as a liquid, given only the project ID, it would have to query Keystone for name and domain association on every single usage report. I find that excessive, esp. considering that Limes already has this information available.
This change also adds the same signaling to ServiceQuotaRequest. This will be useful for liquid-swift: It needs the domain ID when setting quota. Since SetQuota is rarer than ReportUsage, I considered it fine there to just query Keystone directly, but if we're changing this anyway, we're making the full change.
Zooming out into the big picture, this PR demonstrates how I intend to evolve the LIQUID spec in a …
=> liquid: add ProjectMetadata signaling mechanism

limes/resources/commitment.go
To convert a commitment to another resource type I plan to introduce two API endpoints.
The first one is a GET `/v1/commitments/{service_type}/{resource_name}` endpoint. It reads the configuration data of a resource type and decides if a commitment can be converted to a target resource. For this I would like to include the API type from this PR wich includes the amount and the resource type a commitment might be converted to.
(We could also include this information to the GET commitments endpoint, but I would rather not include this information to every single commitment. Because:
a: We would lose the conversion information if we have no matching commitment
b: We add a load of duplicate data to the commitments and the response JSON.)
The second one will be a POST endpoint that receives …
=> Add conversion API type

cadf/event.go, limes/unit_test.go
In a specific case, we are renaming the id to be project_id now for multiple reasons.
if [target][id] and [target][typeURI] == "data/security/project" {
mutate {
id => "f06c_move_target_id_to_project_id"
add_field => { "[target][project_id]" => "%{[target][id]}" }
remove_field => [ "[target][id]" ]
}
}
This means that we need to make ID omitempty as we remove id when it moves to project_id in cases this occurs. 
I can't think of any issues with doing this. If it doesn't exist, it shouldn't be returned.
=> cadf resource id omit empty

liquid/doc.go, liquid/info.go, liquid/report_capacity.go, liquid/report_usage.go
This is modeled on the existing `QuotaPlugin.ScrapeRates` facility in Limes. The rate scraping and resource scraping are currently split in Limes, but I intend to merge them into one loop since there never was any benefit from keeping them separate (and it just creates a bunch of useless parallel structures).
The remark about SerializedState not working for liquids that have resources is because, in Limes, `serializedState` is only carried through `ScrapeRates` and not through `Scrape` (the latter of which handles resources).
I also used the opportunity to add some more `omitempty` in usage reports where they make sense. This is a backwards-compatible change because Limes does not care either way about map fields being omitted or `null`.
=> liquid: add support for rates

liquid/info.go
As explained in the code comment, this came out of a redundancy that I noticed when writing liquid-ironic.
These attributes will initially not be visible on the Limes v1 API, but I plan to use them as an input for the TranslationRule when translating v2 subcapacities and subresources back into their v1 equivalents.
=> liquid: add ResourceInfo.Attributes

liquid/doc.go, liquid/info.go, liquid/quota.go, liquid/report_capacity.go, liquid/report_usage.go
This is becoming a requirement for liquid-ceph: We will have several storage classes grouped into a single resource as the resource's AZ slots. Using placeholder names for illustrative purposes, there might be several storage classes like:
- "3 replicas in AZ a"
- "3 replicas in AZ b"
- and so on
I recommended against modelling those as separate AZ-unaware resources, so these will be grouped into a single resource "3 replicas in the same AZ". The main consequence from this is that LIQUID needs to add support for AZ-aware quotas (instead of just AZ-aware capacity and usage).
So an additional configuration is needed in `type ResourceInfo`. To avoid turning ResourceInfo into a sea of interconnected booleans, I'm introducing a new enum `type ResourceTopology`. The existing two behaviors are …
=> liquid: add support for AZ-aware quotas

liquid/availability_zone.go
This is a pattern that keeps appearing across liquids, esp. now that Limes has gotten stricter about rejecting unexpected AZ values.
=> liquid: add func NormalizeAZ()

liquid/info.go, liquid/quota.go, liquid/report_capacity.go, liquid/report_usage.go
This is an oversight on my part. RateUsageReport.PerAZ is already documented as being AZ-aware in the same way as
ResourceUsageReport.PerAZ, so we need a topology declaration.
The name change from ResourceTopology to Topology is necessitated by Topology being relevant for rates, too, not just resources.
=> liquid: rename ResourceTopology to Topology, add Topology field to RateInfo

liquid/validation.go
I noticed that the limes tests are flaky within the pipeline.
The reason is that the toplogy tests check multiple invalid resource configurations and expects a given error result.
Without sorting the errors here the testsuit fails ocasionally.
=> [toplogy] sort errors by resource name and rate type

go.mod, go.sum, liquid/quota.go, liquid/report_capacity.go, liquid/report_usage.go, liquid/subdivisions.go, liquid/validation.go, liquid/validation_test.go
In a wildly unexpected move, this adds a **dependency** to go-api-declarations. \*audience gasps audibly\*
Jokes aside, this touches all places where pointer types are used to denote optionality throughout all LIQUID types. Places in which pointers are used for interior mutability are left as is.
`Rate.PerAZ[].Usage` is a bit of a weird case: Previously, we used nil to denote absence, so this becomes an `Option[]` type. But the payload type is still `*big.Int` because the API for big.Int only allows bigints to be passed by reference. A validation is added to forbid the value `Some(nil)`. At the same time, I'm adding a validation to forbid `None` for rates with `HasUsage = true`.
=> liquid: adopt type Option as a replacement for pointers

cadf/event.go, limes/rates/window.go, limes/resources/commitment.go, limes/resources/report_project.go
Most of these are removing ineffective `omitempty` on struct members. For context, structs can never match the condition behind `omitempty`, as explained on the docs of [`json.Marshal`](https://pkg.go.dev/encoding/json#Marshal):
> The "omitempty" option specifies that the field should be omitted from the encoding if the field has an empty value, defined as false, 0, a nil pointer, a nil interface value, and any array, slice, map, or string of length zero.
=> run `modernize -fix ./...`

liquid/availability_zone.go, liquid/doc.go, liquid/validation.go, liquid/validation_test.go
Because the "service/resource" notation for resources is well-established, and the "service/resource/az" notation for AZ resources is establishing itself, I would like to explicitly forbid slashes from occurring in service types and resource names.
If we're doing a validation at all, I feel like we can be slightly more restrictive than just "no slashes", though, so this commit establishes a rule that resource names and rate names must basically look like C identifiers, except that dashes and dots are also allowed. This matches all existing resource names in production.
For rate names, the situation is a bit weirder, because we have two competing precedents:
- For rates reporting usage (currently only Ceph), rate names look like resource names, e.g. `attachment_size` or `recipients`.
- For …
=> liquid: add validation for resource/rate/AZ names, reserve pseudo-AZ "total"

liquid/commitment.go, liquid/commitment_test.go, liquid/doc.go
The `Commitment.UUID` type change is mainly a style-question. I am happy to remove this, if we want to stick to the local definition in `datamodel` of limes.
=> Extensions to the liquid commitment delegation

internal/clone/clone.go, internal/testhelper/clone.go, liquid/commitment.go, liquid/commitment_test.go, liquid/info.go, liquid/info_test.go, liquid/metrics.go, liquid/quota.go, liquid/quota_test.go, liquid/report_capacity.go, liquid/report_capacity_test.go, liquid/report_usage.go, liquid/report_usage_test.go, liquid/subdivisions.go
Similar capabilities already exist in Limes privately, for the purposes of implementing test doubles. Moving this here will ensure that the Clone() implementations are updated together with the types they are based on, thus avoiding accidental implementation drift.
=> liquid: add Clone() methods to all non-trivial types
